//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public long ID { get; set; }
        public byte[] ImageContent { get; set; }
        public string MimeType { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> PostID { get; set; }
        public long UserID { get; set; }
    
        public virtual Posts Posts { get; set; }
    }
}
