//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public long ID { get; set; }
        public byte[] ImageContent { get; set; }
        public string MimeType { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> PostID { get; set; }
        public long UserID { get; set; }
    
        public virtual Posts Posts { get; set; }
    }
}
